package com.shiostudios.dumplingrings.core.engine

import com.shiostudios.dumplingrings.core.geometry.Geometry
import com.shiostudios.dumplingrings.core.geometry.PassTable
import com.shiostudios.dumplingrings.core.model.LevelDefinition
import com.shiostudios.dumplingrings.core.model.ObstacleDef
import com.shiostudios.dumplingrings.core.model.RingDef
import com.shiostudios.dumplingrings.core.model.WeavePattern

/**
 * Discrete, immutable mechanical game state. Everything the rules depend on lives here:
 * ring angle indices (angle = index * stepDeg) and the removed flags. Nothing decorative.
 */
class GameState(val angles: IntArray, val removed: BooleanArray) {
    val activeCount: Int get() = removed.count { !it }
    val isWin: Boolean get() = removed.all { it }
    fun copy(): GameState = GameState(angles.copyOf(), removed.copyOf())
    fun key(): StateKey = StateKey(angles, removed)
    override fun equals(other: Any?): Boolean =
        other is GameState && angles.contentEquals(other.angles) && removed.contentEquals(other.removed)
    override fun hashCode(): Int = 31 * angles.contentHashCode() + removed.contentHashCode()
}

/** Compact hashable key (packed into longs) for solver transposition tables. */
class StateKey(angles: IntArray, removed: BooleanArray) {
    private val a: Long
    private val b: Long
    init {
        var x = 0L; var y = 0L
        for (i in angles.indices) {
            val v = (angles[i].toLong() and 31L) or (if (removed[i]) 32L else 0L) // 6 bits per ring
            if (i < 10) x = x or (v shl (6 * i)) else y = y or (v shl (6 * (i - 10)))
        }
        a = x; b = y
    }
    override fun equals(other: Any?) = other is StateKey && other.a == a && other.b == b
    override fun hashCode(): Int = (a xor (a ushr 32) xor (b * 1000003L) xor (b ushr 29)).toInt()
}

sealed class LegalAction {
    /** Rotate ring [ring] so that its angle index becomes [target]. One drag = one move. */
    data class RotateTo(val ring: Int, val target: Int) : LegalAction()
    /** Booster action (Golden Steamer): lift the ring out regardless of blockers. Never generated by the solver. */
    data class ForceRelease(val ring: Int) : LegalAction()
}

/** A wave of rings released together after one move (combo = several waves or several rings in one wave). */
data class ReleaseWave(val rings: List<Int>)

data class ActionResult(
    val legal: Boolean,
    val state: GameState,
    val releases: List<ReleaseWave> = emptyList(),
    val reason: String? = null,
) {
    val releasedRings: List<Int> get() = releases.flatMap { it.rings }
}

/**
 * The compiled, immutable rule set for one level: pass tables, lock/link groups and arc limits.
 * Pure Kotlin, deterministic, shared by gameplay, solver, hints, tests and tools.
 */
class RuleEngine(val level: LevelDefinition) {
    val rings: List<RingDef> = level.rings
    val n = rings.size
    val ringIndex: Map<String, Int> = rings.withIndex().associate { it.value.id to it.index }
    val steps = IntArray(n) { 360 / rings[it].stepDeg }
    val stepDeg = IntArray(n) { rings[it].stepDeg }

    /** pairPass[mover][blocker] : PassTable(moverSteps, blockerSteps), null if the blocker can never obstruct the mover. */
    val pairPass: Array<Array<PassTable?>> = Array(n) { arrayOfNulls<PassTable>(n) }

    /** obstacle driver ring index per obstacle (-1 = static). */
    val obstacles: List<ObstacleDef> = level.obstacles
    val obstacleDriver = IntArray(obstacles.size) { i -> obstacles[i].linkedRingId?.let { ringIndex[it] } ?: -1 }
    /** obstaclePass[mover][obstacle] : PassTable(moverSteps, driverSteps or 1), null if never obstructs / colour exempt. */
    val obstaclePass: Array<Array<PassTable?>> = Array(n) { arrayOfNulls<PassTable>(obstacles.size) }

    val lockedBy: Array<IntArray> = Array(n) { i -> rings[i].lockedBy.map { ringIndex.getValue(it) }.toIntArray() }
    /** Members of each ring's link group (including itself). */
    val group: Array<IntArray>
    val allowed: Array<BooleanArray> = Array(n) { i ->
        val r = rings[i]
        BooleanArray(steps[i]) { idx ->
            val deg = idx * r.stepDeg
            val arc = r.arc
            if (arc == null) true else {
                val span = Geometry.normDegInt(arc.maxDeg - arc.minDeg)
                Geometry.normDegInt(deg - arc.minDeg) <= span
            }
        }
    }

    init {
        require(n in 1..20) { "ring count out of range" }
        rings.forEach { r ->
            require(360 % r.stepDeg == 0) { "stepDeg must divide 360" }
            require(r.initialAngleDeg % r.stepDeg == 0) { "initial angle must be a multiple of stepDeg (${r.id})" }
            require(r.gaps.isNotEmpty()) { "ring ${r.id} needs at least one gap" }
        }
        val groups = HashMap<String, MutableList<Int>>()
        rings.forEachIndexed { i, r -> r.linkGroup?.let { groups.getOrPut(it) { ArrayList() }.add(i) } }
        groups.values.forEach { g ->
            val s = g.map { steps[it] }.toSet()
            require(s.size == 1) { "linked rings must share stepDeg" }
        }
        group = Array(n) { i -> rings[i].linkGroup?.let { groups.getValue(it).toIntArray() } ?: intArrayOf(i) }
        compileTables()
    }

    /** weave pattern for ordered pair (a,b) from a's perspective */
    fun weave(a: Int, b: Int): WeavePattern {
        val ra = rings[a].id; val rb = rings[b].id
        level.weaves.firstOrNull { it.a == ra && it.b == rb }?.let { return it.pattern }
        level.weaves.firstOrNull { it.a == rb && it.b == ra }?.let { return flip(it.pattern, b, a) }
        return if (a < b) WeavePattern.ALT1 else flip(WeavePattern.ALT1, b, a)
    }

    /** Express pattern given from `from`'s perspective in `to`'s perspective (crossings are re-sorted around `to`). */
    private fun flip(p: WeavePattern, from: Int, to: Int): WeavePattern {
        val cf = Geometry.crossings(rings[from], rings[to])
        val ct = Geometry.crossings(rings[to], rings[from])
        if (cf.size < 2 || ct.size < 2) return WeavePattern.ALT1
        // does crossing 0 of `to` correspond to crossing 0 of `from`?
        val same = (cf[0].x - ct[0].x).let { it * it } + (cf[0].y - ct[0].y).let { it * it } < 1e-12
        return when (p) {
            WeavePattern.A_OVER -> WeavePattern.B_OVER
            WeavePattern.B_OVER -> WeavePattern.A_OVER
            WeavePattern.ALT1 -> if (same) WeavePattern.ALT2 else WeavePattern.ALT1
            WeavePattern.ALT2 -> if (same) WeavePattern.ALT1 else WeavePattern.ALT2
        }
    }

    private fun compileTables() {
        // ring vs ring: wire of b that lies over a (per weave pattern) must fit in a's gaps
        for (a in 0 until n) for (b in 0 until n) {
            if (a == b) continue
            val ra = rings[a]; val rb = rings[b]
            if (!Geometry.circlesCross(ra, rb)) continue
            val pattern = weave(a, b)
            val t = PassTable(steps[a], steps[b])
            var any = false
            val wires = Array(steps[b]) { Geometry.overWire(ra, rb, Geometry.ringWire(rb, (it * rb.stepDeg).toDouble()), pattern) }
            for (ia in 0 until steps[a]) for (ib in 0 until steps[b]) {
                val ok = Geometry.canLiftPast(ra, (ia * ra.stepDeg).toDouble(), wires[ib], rb.thickness)
                t[ia, ib] = ok
                if (!ok) any = true
            }
            if (any) pairPass[a][b] = t
        }
        // ring vs obstacle (obstacles always rest on top)
        for (a in 0 until n) for (o in obstacles.indices) {
            val ra = rings[a]; val ob = obstacles[o]
            if (ob.colorId != null && ob.colorId == ra.colorId) continue
            val drv = obstacleDriver[o]
            val cols = if (drv >= 0) steps[drv] else 1
            val t = PassTable(steps[a], cols)
            var any = false
            val wires = Array(cols) { Geometry.obstacleWire(ob, if (drv >= 0) (it * stepDeg[drv]).toDouble() else 0.0) }
            for (ia in 0 until steps[a]) for (ic in 0 until cols) {
                val ok = Geometry.canLiftPast(ra, (ia * ra.stepDeg).toDouble(), wires[ic], ob.thickness)
                t[ia, ic] = ok
                if (!ok) any = true
            }
            if (any) obstaclePass[a][o] = t
        }
    }

    fun initialState(): GameState = GameState(IntArray(n) { Geometry.normDegInt(rings[it].initialAngleDeg) / stepDeg[it] }, BooleanArray(n))

    fun angleDeg(state: GameState, ring: Int): Int = state.angles[ring] * stepDeg[ring]

    fun isLocked(state: GameState, ring: Int): Boolean = lockedBy[ring].any { !state.removed[it] }

    /** Active members of the ring's link group (removed rings drop out of the chain). */
    fun activeGroup(state: GameState, ring: Int): List<Int> = group[ring].filter { !state.removed[it] }

    /** The ring's (active) link group must be unlocked for it to rotate. */
    fun canRotate(state: GameState, ring: Int): Boolean {
        if (state.removed[ring]) return false
        val g = activeGroup(state, ring)
        return g.none { isLocked(state, it) } && allowed[ring].count { it } > 1
    }

    fun canRelease(state: GameState, ring: Int): Boolean {
        if (state.removed[ring]) return false
        if (isLocked(state, ring)) return false
        val ia = state.angles[ring]
        for (b in 0 until n) {
            if (b == ring || state.removed[b]) continue
            val t = pairPass[ring][b] ?: continue
            if (!t[ia, state.angles[b]]) return false
        }
        for (o in obstacles.indices) {
            val t = obstaclePass[ring][o] ?: continue
            val drv = obstacleDriver[o]
            val col = if (drv >= 0) { if (state.removed[drv]) continue else state.angles[drv] } else 0
            if (!t[ia, col]) return false
        }
        return true
    }

    /** Number of active bodies blocking this ring right now (allocation-free, for solver heuristics). */
    fun blockerCount(state: GameState, ring: Int): Int {
        var c = 0
        if (isLocked(state, ring)) c += lockedBy[ring].count { !state.removed[it] }
        val ia = state.angles[ring]
        for (b in 0 until n) {
            if (b == ring || state.removed[b]) continue
            val t = pairPass[ring][b] ?: continue
            if (!t[ia, state.angles[b]]) c++
        }
        for (o in obstacles.indices) {
            val t = obstaclePass[ring][o] ?: continue
            val drv = obstacleDriver[o]
            val col = if (drv >= 0) { if (state.removed[drv]) continue else state.angles[drv] } else 0
            if (!t[ia, col]) c++
        }
        return c
    }

    /** Which other active bodies block this ring right now (for hints / tutorial explanations). */
    fun blockers(state: GameState, ring: Int): List<String> {
        val out = ArrayList<String>()
        if (isLocked(state, ring)) lockedBy[ring].filter { !state.removed[it] }.forEach { out.add("lock:" + rings[it].id) }
        val ia = state.angles[ring]
        for (b in 0 until n) {
            if (b == ring || state.removed[b]) continue
            val t = pairPass[ring][b] ?: continue
            if (!t[ia, state.angles[b]]) out.add("ring:" + rings[b].id)
        }
        for (o in obstacles.indices) {
            val t = obstaclePass[ring][o] ?: continue
            val drv = obstacleDriver[o]
            val col = if (drv >= 0) { if (state.removed[drv]) continue else state.angles[drv] } else 0
            if (!t[ia, col]) out.add("obstacle:" + obstacles[o].id)
        }
        return out
    }

    /**
     * Compute the angle indices of all group members after rotating [ring] to [target], or null if the
     * rotation is illegal (locked, removed, or any member would leave its allowed arc on the way).
     */
    fun rotatedAngles(state: GameState, ring: Int, target: Int): IntArray? {
        if (!canRotate(state, ring)) return null
        val st = steps[ring]
        val tgt = ((target % st) + st) % st
        val cur = state.angles[ring]
        if (tgt == cur) return null
        if (!allowed[ring][tgt]) return null
        val members = activeGroup(state, ring)
        val ratioSelf = rings[ring].linkRatio
        val deltas = intArrayOf(tgt - cur, if (tgt - cur > 0) tgt - cur - st else tgt - cur + st)
        for (delta in deltas) {
            val res = state.angles.copyOf()
            var ok = true
            for (m in members) {
                val sign = ratioSelf * rings[m].linkRatio
                val d = delta * sign
                // walk the path step by step to verify the arc is never left
                var a = state.angles[m]
                val stepDir = if (d > 0) 1 else -1
                for (k in 1..kotlin.math.abs(d)) {
                    a = ((a + stepDir) % st + st) % st
                    if (!allowed[m][a]) { ok = false; break }
                }
                if (!ok) break
                res[m] = a
            }
            if (ok) return res
        }
        return null
    }

    /** Apply the move, then cascade releases. Returns the resulting state and release waves. */
    fun apply(state: GameState, action: LegalAction): ActionResult = when (action) {
        is LegalAction.ForceRelease -> {
            if (state.removed[action.ring]) ActionResult(false, state, reason = "already removed")
            else {
                val next = GameState(state.angles.copyOf(), state.removed.copyOf())
                next.removed[action.ring] = true
                val waves = listOf(ReleaseWave(listOf(action.ring))) + cascade(next)
                ActionResult(true, next, waves)
            }
        }
        is LegalAction.RotateTo -> {
            val angles = rotatedAngles(state, action.ring, action.target)
            if (angles == null) ActionResult(false, state, reason = "illegal rotation")
            else {
                val next = GameState(angles, state.removed.copyOf())
                val waves = cascade(next)
                ActionResult(true, next, waves)
            }
        }
    }

    /** Remove every releasable ring, repeatedly, mutating [s]. Deterministic order (index order within a wave). */
    fun cascade(s: GameState): List<ReleaseWave> {
        val waves = ArrayList<ReleaseWave>()
        while (true) {
            val rel = (0 until n).filter { canRelease(s, it) }
            if (rel.isEmpty()) break
            rel.forEach { s.removed[it] = true }
            waves.add(ReleaseWave(rel))
        }
        return waves
    }

    /** Candidate target angle indices per ring that are logically distinct (signature pruning for the solver). */
    val meaningfulTargets: Array<IntArray> by lazy { computeMeaningful() }

    private fun computeMeaningful(): Array<IntArray> {
        return Array(n) { i ->
            val sigs = LinkedHashMap<String, Int>()
            for (idx in 0 until steps[i]) {
                if (!allowed[i][idx]) continue
                val sb = StringBuilder()
                for (b in 0 until n) {
                    pairPass[i][b]?.let { sb.append('m').append(it.row(idx).joinToString("") { v -> if (v) "1" else "0" }) }
                    pairPass[b][i]?.let { sb.append('b').append(it.col(idx).joinToString("") { v -> if (v) "1" else "0" }) }
                }
                for (o in obstacles.indices) {
                    obstaclePass[i][o]?.let { sb.append('o').append(it.row(idx).joinToString("") { v -> if (v) "1" else "0" }) }
                    if (obstacleDriver[o] == i) for (m in 0 until n) obstaclePass[m][o]?.let { sb.append('d').append(it.col(idx).joinToString("") { v -> if (v) "1" else "0" }) }
                }
                val key = sb.toString()
                if (!sigs.containsKey(key)) sigs[key] = idx
            }
            sigs.values.toIntArray()
        }
    }

    /**
     * All legal actions from a state for the solver and hints. Two safe prunings keep the branching small:
     *  1. angles with an identical full pass signature are merged ([meaningfulTargets]);
     *  2. a rotation that flips no pass bit relative to the *current* partner angles is dropped — it can always be
     *     deferred to the moment it has an effect without changing the move count (moves commute, locks only ever open).
     */
    fun legalActions(state: GameState): List<LegalAction.RotateTo> {
        val out = ArrayList<LegalAction.RotateTo>()
        for (i in 0 until n) {
            if (!canRotate(state, i)) continue
            val g = activeGroup(state, i)
            if (g.min() != i) continue
            val targets = LinkedHashSet<Int>()
            for (t in meaningfulTargets[i]) targets.add(t)
            for (m in g) if (m != i) {
                val sign = rings[i].linkRatio * rings[m].linkRatio
                for (tm in meaningfulTargets[m]) {
                    val d = (tm - state.angles[m]) * sign
                    targets.add(((state.angles[i] + d) % steps[i] + steps[i]) % steps[i])
                }
            }
            for (t in targets) {
                if (t == state.angles[i]) continue
                val angles = rotatedAngles(state, i, t) ?: continue
                if (!changesAnyBit(state, angles, g)) continue
                out.add(LegalAction.RotateTo(i, t))
            }
        }
        return out
    }

    /** Does moving the group members to `angles` flip any pass bit versus the current state? */
    private fun changesAnyBit(state: GameState, angles: IntArray, members: List<Int>): Boolean {
        for (m in members) {
            val a0 = state.angles[m]; val a1 = angles[m]
            if (a0 == a1) continue
            for (b in 0 until n) {
                if (b == m || state.removed[b]) continue
                val ab = angles[b]
                pairPass[m][b]?.let { if (it[a0, state.angles[b]] != it[a1, ab]) return true }
                pairPass[b][m]?.let { if (it[state.angles[b], a0] != it[ab, a1]) return true }
            }
            for (o in obstacles.indices) {
                val drv = obstacleDriver[o]
                val c0 = if (drv >= 0) { if (state.removed[drv]) continue else state.angles[drv] } else 0
                val c1 = if (drv >= 0) angles[drv] else 0
                obstaclePass[m][o]?.let { if (it[a0, c0] != it[a1, c1]) return true }
                if (drv == m) for (k in 0 until n) if (!state.removed[k]) obstaclePass[k][o]?.let { if (it[state.angles[k], a0] != it[angles[k], a1]) return true }
            }
        }
        return false
    }

    /** Stable hash of the topology (geometry + mechanics, ignoring initial angles) for duplicate detection. */
    fun topologyHash(): String {
        val sb = StringBuilder()
        rings.sortedBy { it.id }.forEach { r ->
            sb.append(r.id).append(':').append("%.3f,%.3f,%.3f,%.3f".format(r.center[0], r.center[1], r.radius, r.thickness))
            sb.append('|').append(r.gaps.joinToString(",") { "%.0f/%.0f".format(it.startDeg, it.widthDeg) })
            sb.append('|').append(r.exitAngleDeg).append('|').append(r.arc).append('|').append(r.lockedBy)
            sb.append('|').append(r.linkGroup).append(r.linkRatio).append('|').append(r.colorId).append(';')
        }
        obstacles.forEach { sb.append(it.toString()).append(';') }
        var h = 1469598103934665603L
        for (ch in sb) { h = (h xor ch.code.toLong()) * 1099511628211L }
        return java.lang.Long.toHexString(h)
    }
}

/**
 * Single action dispatcher used by gameplay: keeps history for free unlimited undo and exposes the
 * current state. Boosters and hints go through the same [RuleEngine] so they can never corrupt a level.
 */
class GameSession(val engine: RuleEngine, initial: GameState = engine.initialState()) {
    private val history = ArrayList<GameState>()
    var state: GameState = initial
        private set
    var moves: Int = 0
        private set
    val canUndo: Boolean get() = history.isNotEmpty()
    val isWin: Boolean get() = state.isWin

    fun dispatch(action: LegalAction): ActionResult {
        val res = engine.apply(state, action)
        if (res.legal) {
            history.add(state)
            state = res.state
            moves++
        }
        return res
    }

    fun undo(): Boolean {
        if (history.isEmpty()) return false
        state = history.removeAt(history.size - 1)
        moves--
        return true
    }

    fun restart() {
        history.clear()
        state = engine.initialState()
        moves = 0
    }

    /** Restore a snapshot (used when resuming a level from the save store). */
    fun restore(angles: IntArray, removed: BooleanArray, moves: Int) {
        history.clear()
        state = GameState(angles.copyOf(), removed.copyOf())
        this.moves = moves
    }
}
